name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Unit tests
        run: |
          CGO_ENABLED=0 go test ./...
          CGO_ENABLED=1 go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57.2
